(function typingContentModule(root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }
  root.CSTypingContent = factory();
})(typeof globalThis !== "undefined" ? globalThis : window, function createTypingContent() {
  "use strict";

  var ALL_GRADES = ["K-2", "3-5", "6-8", "9-12"];

  return [
    {
      id: "typing-u0-l1",
      lessonOrder: 1,
      unitLabel: "Unit 0",
      lessonLabel: "Lesson 1",
      stageLabel: "Anchor keys",
      prompt: "Start on the anchor keys.",
      target: "fjfj",
      typingKind: "keys",
      keyboardZone: "home row anchors",
      orthographyFocus: "finger placement · f / j",
      fingerCue: "Rest your index fingers on the F and J bumps before every try.",
      meaningHint: "Typing starts with anchor keys so hands can return home without looking down.",
      swbat: "I can find F and J without looking down at the keyboard.",
      masteryGoalWpm: 8,
      masteryGoalAccuracy: 95,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u0-l2",
      lessonOrder: 2,
      unitLabel: "Unit 0",
      lessonLabel: "Lesson 2",
      stageLabel: "Center sweep",
      prompt: "Sweep across the middle of home row.",
      target: "dfjk",
      typingKind: "keys",
      keyboardZone: "home row",
      orthographyFocus: "finger reach · d / f / j / k",
      fingerCue: "Return to F and J after each tap so the next reach stays controlled.",
      meaningHint: "This is keyboard muscle-memory practice before full words begin.",
      swbat: "I can move from the home anchors to nearby home-row keys and return.",
      masteryGoalWpm: 8,
      masteryGoalAccuracy: 95,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u0-l3",
      lessonOrder: 3,
      unitLabel: "Unit 0",
      lessonLabel: "Lesson 3",
      stageLabel: "Full home row",
      prompt: "Type the full home-row pattern.",
      target: "asdf jkl;",
      typingKind: "keys",
      keyboardZone: "full home row",
      orthographyFocus: "home row automaticity",
      fingerCue: "Keep each finger responsible for its own key and keep your wrists quiet.",
      meaningHint: "A full home-row sweep prepares students to type short words with rhythm.",
      swbat: "I can move across the home row with steady finger control.",
      masteryGoalWpm: 10,
      masteryGoalAccuracy: 95,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u0-l4",
      lessonOrder: 4,
      unitLabel: "Unit 0",
      lessonLabel: "Lesson 4",
      stageLabel: "Anchor rhythm",
      prompt: "Type the anchor rhythm.",
      target: "fff jjj",
      typingKind: "keys",
      keyboardZone: "home row anchors + space bar",
      orthographyFocus: "anchor automaticity",
      fingerCue: "Stay relaxed and repeat the pattern without glancing down.",
      meaningHint: "Repeating the anchor keys builds confidence before the first real words appear.",
      swbat: "I can keep a steady rhythm on the home anchors.",
      masteryGoalWpm: 10,
      masteryGoalAccuracy: 96,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u1-l1",
      lessonOrder: 5,
      unitLabel: "Unit 1",
      lessonLabel: "Lesson 5",
      stageLabel: "Short a word",
      prompt: "Type the short-a word.",
      target: "sad",
      typingKind: "word",
      keyboardZone: "home row",
      orthographyFocus: "CVC · short a",
      fingerCue: "Say each sound quickly, then type the whole word as one smooth movement.",
      meaningHint: "Short-a CVC words let students connect sound mapping to keyboard rhythm.",
      swbat: "I can type a short-a CVC word using the home row.",
      masteryGoalWpm: 10,
      masteryGoalAccuracy: 96,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u1-l2",
      lessonOrder: 6,
      unitLabel: "Unit 1",
      lessonLabel: "Lesson 6",
      stageLabel: "Short a word",
      prompt: "Type the next short-a word.",
      target: "dad",
      typingKind: "word",
      keyboardZone: "home row",
      orthographyFocus: "CVC · short a",
      fingerCue: "Use the same rhythm as sad, but notice the first sound shifts to /d/.",
      meaningHint: "Keeping the pattern stable helps students notice which part of the word changed.",
      swbat: "I can type another short-a CVC word by changing only one sound.",
      masteryGoalWpm: 10,
      masteryGoalAccuracy: 96,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u1-l3",
      lessonOrder: 7,
      unitLabel: "Unit 1",
      lessonLabel: "Lesson 7",
      stageLabel: "No-excuse word",
      prompt: "Type the no-excuse word.",
      target: "all",
      typingKind: "word",
      keyboardZone: "home row",
      orthographyFocus: "high-frequency word",
      fingerCue: "Keep your eyes on the whole word. This one should become automatic fast.",
      meaningHint: "High-frequency words belong in both reading practice and typing fluency work.",
      swbat: "I can type a high-frequency word from memory.",
      masteryGoalWpm: 11,
      masteryGoalAccuracy: 96,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u1-l4",
      lessonOrder: 8,
      unitLabel: "Unit 1",
      lessonLabel: "Lesson 8",
      stageLabel: "Home-row word",
      prompt: "Type the home-row word.",
      target: "fall",
      typingKind: "word",
      keyboardZone: "home row",
      orthographyFocus: "closed syllable · short a",
      fingerCue: "Notice the same short-a sound, then keep the two l letters together at the end.",
      meaningHint: "Students keep the short-vowel pattern while typing a slightly longer word.",
      swbat: "I can type a longer home-row word with steady rhythm.",
      masteryGoalWpm: 11,
      masteryGoalAccuracy: 96,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u1-l5",
      lessonOrder: 9,
      unitLabel: "Unit 1",
      lessonLabel: "Lesson 9",
      stageLabel: "Home-row phrase",
      prompt: "Type the home-row phrase.",
      target: "sad dad",
      typingKind: "phrase",
      keyboardZone: "home row + space bar",
      orthographyFocus: "phrase fluency · short a",
      fingerCue: "Keep your thumbs ready for the space bar so the phrase still feels continuous.",
      meaningHint: "Phrase typing starts building eye-tracking and spacing habits, not just single words.",
      swbat: "I can type two decodable words with the right spacing.",
      masteryGoalWpm: 12,
      masteryGoalAccuracy: 96,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u2-l1",
      lessonOrder: 10,
      unitLabel: "Unit 2",
      lessonLabel: "Lesson 10",
      stageLabel: "Top row word",
      prompt: "Reach up for the top-row word.",
      target: "it",
      typingKind: "word",
      keyboardZone: "home row + top row",
      orthographyFocus: "high-frequency word",
      fingerCue: "Lift only the finger you need to the top row, then return home.",
      meaningHint: "Top-row reach should stay small and controlled so accuracy stays high.",
      swbat: "I can reach to the top row and return to home row smoothly.",
      masteryGoalWpm: 12,
      masteryGoalAccuracy: 97,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u2-l2",
      lessonOrder: 11,
      unitLabel: "Unit 2",
      lessonLabel: "Lesson 11",
      stageLabel: "Top row word",
      prompt: "Type the high-frequency word.",
      target: "is",
      typingKind: "word",
      keyboardZone: "home row + top row",
      orthographyFocus: "high-frequency word",
      fingerCue: "Hold home-row posture even while the top-row finger reaches up for i.",
      meaningHint: "Students see this word constantly in connected text, so automaticity matters.",
      swbat: "I can type a top-row high-frequency word with control.",
      masteryGoalWpm: 12,
      masteryGoalAccuracy: 97,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u2-l3",
      lessonOrder: 12,
      unitLabel: "Unit 2",
      lessonLabel: "Lesson 12",
      stageLabel: "Top row phrase",
      prompt: "Type the phrase.",
      target: "it is",
      typingKind: "phrase",
      keyboardZone: "home row + top row + space bar",
      orthographyFocus: "high-frequency phrase",
      fingerCue: "Try not to pause between words. Let the phrase move as one chunk.",
      meaningHint: "Short phrases let students keep top-row reaches small while spacing stays accurate.",
      swbat: "I can type a short top-row phrase with spacing and control.",
      masteryGoalWpm: 13,
      masteryGoalAccuracy: 97,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u2-l4",
      lessonOrder: 13,
      unitLabel: "Unit 2",
      lessonLabel: "Lesson 13",
      stageLabel: "Heart word",
      prompt: "Type the heart word.",
      target: "said",
      typingKind: "word",
      keyboardZone: "home row + top row",
      orthographyFocus: "heart word · ai",
      fingerCue: "Say the whole word, then notice that ai is the part you have to remember by heart.",
      meaningHint: "Heart-word typing should spotlight the irregular part instead of treating the word as random.",
      swbat: "I can type a heart word and name the letters I have to remember by heart.",
      masteryGoalWpm: 13,
      masteryGoalAccuracy: 97,
      heartLetters: "ai",
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u2-l5",
      lessonOrder: 14,
      unitLabel: "Unit 2",
      lessonLabel: "Lesson 14",
      stageLabel: "Heart word",
      prompt: "Type the no-excuse word.",
      target: "the",
      typingKind: "word",
      keyboardZone: "home row + top row",
      orthographyFocus: "heart word · e",
      fingerCue: "Lock in th first, then remember the ending vowel by heart.",
      meaningHint: "This word should become automatic because it appears in nearly every text students read.",
      swbat: "I can type the word the and remember the part that is not fully regular.",
      masteryGoalWpm: 13,
      masteryGoalAccuracy: 97,
      heartLetters: "e",
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u3-l1",
      lessonOrder: 15,
      unitLabel: "Unit 3",
      lessonLabel: "Lesson 15",
      stageLabel: "Bottom row word",
      prompt: "Type the bottom-row word.",
      target: "am",
      typingKind: "word",
      keyboardZone: "home row + bottom row",
      orthographyFocus: "high-frequency word",
      fingerCue: "Drop to the bottom row and come right back to home row after the reach.",
      meaningHint: "Bottom-row control matters once students begin typing more connected text.",
      swbat: "I can reach to the bottom row and return without losing accuracy.",
      masteryGoalWpm: 14,
      masteryGoalAccuracy: 97,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u3-l2",
      lessonOrder: 16,
      unitLabel: "Unit 3",
      lessonLabel: "Lesson 16",
      stageLabel: "Bottom row word",
      prompt: "Type the bottom-row short-a word.",
      target: "jam",
      typingKind: "word",
      keyboardZone: "home row + bottom row",
      orthographyFocus: "CVC · short a",
      fingerCue: "Keep the same short-a pattern, but let the first and last fingers travel farther this time.",
      meaningHint: "Students keep the phonics pattern stable while keyboard demand increases.",
      swbat: "I can type a short-a word that includes a bottom-row reach.",
      masteryGoalWpm: 14,
      masteryGoalAccuracy: 97,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u3-l3",
      lessonOrder: 17,
      unitLabel: "Unit 3",
      lessonLabel: "Lesson 17",
      stageLabel: "Digraph word",
      prompt: "Type the digraph word.",
      target: "that",
      typingKind: "word",
      keyboardZone: "home row + top row",
      orthographyFocus: "digraph th",
      fingerCue: "See th as one chunk before you start, then finish the rest of the word without breaking it apart.",
      meaningHint: "Digraph lessons should reinforce that two letters can map to one phoneme while hands still move smoothly.",
      swbat: "I can type a word with th as one connected chunk.",
      masteryGoalWpm: 15,
      masteryGoalAccuracy: 97,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u3-l4",
      lessonOrder: 18,
      unitLabel: "Unit 3",
      lessonLabel: "Lesson 18",
      stageLabel: "Digraph phrase",
      prompt: "Type the connected phrase.",
      target: "this is",
      typingKind: "phrase",
      keyboardZone: "home row + top row + space bar",
      orthographyFocus: "digraph th + high-frequency word",
      fingerCue: "Let th stay together, then keep your hands relaxed as you move into the next word.",
      meaningHint: "Connected phrase work supports fluency, spacing, and common sentence openings.",
      swbat: "I can type a short phrase that includes a digraph and a high-frequency word.",
      masteryGoalWpm: 16,
      masteryGoalAccuracy: 97,
      gradeBands: ALL_GRADES
    },
    {
      id: "typing-u4-l1",
      lessonOrder: 19,
      unitLabel: "Unit 4",
      lessonLabel: "Lesson 19",
      stageLabel: "Connected phrase",
      prompt: "Type the lesson phrase.",
      target: "read it",
      typingKind: "phrase",
      keyboardZone: "full keyboard + space bar",
      orthographyFocus: "vowel team ea",
      fingerCue: "Chunk the phrase into read + it, then type it with one steady tempo.",
      meaningHint: "Typing short lesson phrases starts preparing students for connected-text fluency.",
      swbat: "I can type a short lesson phrase with accurate spacing and smooth rhythm.",
      masteryGoalWpm: 17,
      masteryGoalAccuracy: 97,
      gradeBands: ["3-5", "6-8", "9-12"]
    },
    {
      id: "typing-u4-l2",
      lessonOrder: 20,
      unitLabel: "Unit 4",
      lessonLabel: "Lesson 20",
      stageLabel: "Connected phrase",
      prompt: "Type the content phrase.",
      target: "math facts",
      typingKind: "phrase",
      keyboardZone: "full keyboard + space bar",
      orthographyFocus: "content vocabulary phrase",
      fingerCue: "Keep your eyes out front and let your thumbs handle the space smoothly.",
      meaningHint: "Typing should eventually transfer into academic language, not stay isolated in drills.",
      swbat: "I can type a short content phrase with accuracy and pace.",
      masteryGoalWpm: 18,
      masteryGoalAccuracy: 97,
      gradeBands: ["3-5", "6-8", "9-12"]
    }
  ];
});
